on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: conventional_commits
          release_branch: release

      - run: echo "${{ toJson(steps.version.outputs) }}"

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ steps.version.outputs.version }},enable=${{ !startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable={{is_default_branch}}

      - run: |
          echo "${DOCKER_METADATA_OUTPUT_VERSION}"
          echo "${DOCKER_METADATA_OUTPUT_TAGS}"
          echo "${DOCKER_METADATA_OUTPUT_LABELS}"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          helm package ./chart --version ${DOCKER_METADATA_OUTPUT_VERSION} --app-version ${DOCKER_METADATA_OUTPUT_VERSION}
          helm push *.tgz oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts
