on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - run: |
          echo "${DOCKER_METADATA_OUTPUT_VERSION}"
          echo "${DOCKER_METADATA_OUTPUT_TAGS}"
          echo "${DOCKER_METADATA_OUTPUT_LABELS}"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: oras-project/setup-oras@v1
      - run: |
          echo "1" > file.txt
          oras push --annotation "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            ghcr.io/${{ github.repository }}/files:${{ steps.meta.outputs.version }} file.txt
