on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: conventional_commits

      - run: echo "${{ toJson(steps.version.outputs) }}"

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{steps.version.outputs.version}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - run: |
          echo "${DOCKER_METADATA_OUTPUT_VERSION}"
          echo "${DOCKER_METADATA_OUTPUT_TAGS}"
          echo "${DOCKER_METADATA_OUTPUT_LABELS}"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: oras-project/setup-oras@v1
      - run: |
          CHART_NAME=$(yq '.name' chart/Chart.yaml)
          helm package ./chart --version ${DOCKER_METADATA_OUTPUT_VERSION} --app-version ${DOCKER_METADATA_OUTPUT_VERSION}
          oras push --annotation "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}" \
            ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts/${CHART_NAME}:${DOCKER_METADATA_OUTPUT_VERSION} ${CHART_NAME}-${DOCKER_METADATA_OUTPUT_VERSION}.tgz
