on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - run: |
          echo "${{ steps.meta.outputs.version }}"
          echo "${{ steps.meta.outputs.tags }}"
          echo "${{ steps.meta.outputs.labels }}"
          echo "${{ steps.meta.outputs.json }}"

      - run: |
          echo "${DOCKER_METADATA_OUTPUT_VERSION}"
          echo "${DOCKER_METADATA_OUTPUT_TAGS}"
          echo "${DOCKER_METADATA_OUTPUT_LABELS}"
